name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch
  workflow_dispatch:  # Allows manual triggering
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      custom_domain:
        description: 'Custom domain to use (leave empty for default)'
        required: false
        default: 'jeopardy.runthebot.me'
        type: string

# Add permissions for the GitHub token
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust based on your project requirements
          cache: 'gradle'  # Enable built-in Gradle dependency caching

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache libGDX builds
        uses: actions/cache@v3
        with:
          path: html/build
          key: ${{ runner.os }}-html-build-${{ hashFiles('html/src/**', 'core/src/**') }}
          restore-keys: |
            ${{ runner.os }}-html-build-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew html:dist --no-daemon

      - name: Create CNAME file
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ -n "${{ github.event.inputs.custom_domain }}" ]; then
            echo "${{ github.event.inputs.custom_domain }}" > html/build/dist/CNAME
          else
            echo "jeopardy.runthebot.me" > html/build/dist/CNAME
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: html/build/dist  # The folder the action should deploy
          clean: true  # Automatically remove deleted files from the deployment branch
